title: TEDxYouth Minoru Park
email: info.tedxminoruparkyouth@gmail.com
location: XYZ 12000 Road. Richmond, BC
description: >-
  Description
baseurl: "tedxminorupark-site"
url: "https://akixuu.github.io" 
social_links:
  discord: https://discord.gg/JV6YBbHwzJ
  linkedin: https://www.linkedin.com/company/tedxminoru-park-youth/
  instagram: https://www.instagram.com/tedxminoruparkyouth/
  github: https://github.com/TEDxMinoruPark/

plugins:
  - jekyll-loading-lazy
  - jekyll-sass-converter

theme: null

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "wrapper"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
